

create database if not exists  fresco;
use fresco;


create table if not exists h1bb(
CASE_NUMBER varchar(255),
CASE_STATUS varchar(255),
CASE_SUBMITTED varchar(255),	
DECISION_DATE varchar(255), 
VISA_CLASS varchar(255),
EMPLOYMENT_START_DATE varchar(255),
EMPLOYMENT_END_DATE varchar(255),
EMPLOYER_NAME varchar(255),	
EMPLOYER_BUSINESS_DBA varchar(255),	
EMPLOYER_ADDRESS varchar(255),	
EMPLOYER_CITY varchar(255),	
EMPLOYER_STATE varchar(255),	
EMPLOYER_POSTAL_CODE varchar(255),
EMPLOYER_COUNTRY varchar(255),
EMPLOYER_PROVINCE varchar(255),
EMPLOYER_PHONE INT,
EMPLOYER_PHONE_EXT varchar(255),
SECONDARY_ENTITY varchar(255),
SECONDARY_ENTITY_BUSINESS_NAME varchar(255),
AGENT_REPRESENTING_EMPLOYER varchar(255),
AGENT_ATTORNEY_NAME varchar(255), 
AGENT_ATTORNEY_CITY varchar(255),
AGENT_ATTORNEY_STATE varchar(255), 
JOB_TITLE varchar(255),	
SOC_CODE varchar(255),
SOC_NAME varchar(255),
NAICS_CODE BIGINT,
TOTAL_WORKERS varchar(255),
NEW_EMPLOYMENT INT,	
CONTINUED_EMPLOYMENT INT,
CHANGE_PREVIOUS_EMPLOYMENT INT,
NEW_CONCURRENT_EMP INT,
CHANGE_EMPLOYER INT,
AMENDED_PETITION INT,
FULL_TIME_POSITION varchar(255),
SALARY varchar(255),
PW_UNIT_OF_PAY varchar(255),
PW_WAGE_LEVEL varchar(255),
PW_SOURCE varchar(255),	
financial_year INT,
PW_SOURCE_OTHER varchar(255),
WRPF varchar(255),
WRPT varchar(255),	
WAGE_UNIT_OF_PAY varchar(255),
H1B_DEPENDENT varchar(255),
WILLFUL_VIOLATOR varchar(255),
SUPPORT_H1B varchar(255),
STATUTORY_BASIS_APPENDIX_ATTACHMENT varchar(255),
LABOR_CON_AGREE varchar(255),	
PUBLIC_DISCLOSURE_LOCATION varchar(255),
WORKSITE_CITY varchar(255),
WORKSITE_COUNTY varchar(255),
WORKSITE_STATE varchar(255),
WORKSITE_POSTAL_CODE varchar(255),
ORIGINAL_CERT_DATE varchar(255),
PRIMARY KEY (CASE_NUMBER)
);





